# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocopodsDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Pastel', '~> 0.3'
  pod 'DynamicButton', '~> 5.0'
  # Pods for CocopodsDemo

end
